# Generated by Django 4.2 on 2023-04-11 07:53

import base.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_owner_first_name_alter_owner_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
                ('objects', base.manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user_permissions',
        ),
    ]
